package com.linfords.euler

/*
Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
object Problem002 extends App {
  var f = 1
  var g = 2
  var sum = 2
  while (g < 4000000) {
    val n = f + g
    if (n % 2 == 0) {
      sum += n
    }
    f = g
    g = n
    println(f + " " + g + " " + n)
  }
  println("Sum: " + sum)
}